# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run the app

on:
  push:
    branches: [ main ]
    paths:
      - 'src/data.py'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Cache requests
      uses: actions/cache@v2
      with:
        path: ~/.cache/http_cache.sqlite
        key: requests-cache
    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --upgrade-strategy eager -r requirements.txt ; \
    - name: Run the app
      env:
        ES_CLOUD_ID: ${{ secrets.ES_CLOUD_ID }}
        ES_USER: ${{ secrets.ES_USER }}
        ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
      run: |
        python src/app.py
